project:
  type: website
  output-dir: docs

website:
  title: "Fish AI Consortium"
  navbar:
    left:
      - href: our goals.qmd
        text: Our goals
      - href: who are we.qmd
        text: Who are we
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: lux
    css: styles.css
    toc: true



