project:
  type: website
  output-dir: docs

website:
  title: "Fish AI Consortium"
  navbar:
    left:
      - href: our_team.qmd
        text: Our Team
      - href: meetings_seminars.qmd
        text: Meetings and Seminars
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: lux
    css: styles.css
    toc: true



